### ISSUE TITLE
Remove the exemptions for the spellchecker

### ISSUE THREAD

**Issue by jugmac00** [canonical/launchpad-manual#13]
In order to speed up the migration, the spellchecking was disabled for some new pages.

**Comment by sfadriaan** [comment]
@jugmac00 this has been resolved?

**Comment by jugmac00** [comment]
Indeed, it has! Thanks so much for both your and @gerryRcom's support!

This has been resolved, also see https://github.com/canonical/open-documentation-academy/issues/77.
