### ISSUE TITLE
adraoim7@gmail.com

### ISSUE THREAD

**Issue by tbrahtm** [canonical/launchpad-manual#33]
تشغيل 
*Please describe the question or issue you're facing with "Launchpad installation details - Launchpad Manual documentation".*

---
*Reported from: https://documentation.ubuntu.com/launchpad/en/latest/explanation/running-details/*

**Comment by ineesalmeida** [comment]
If you are searching for a career within Launchpad, I suggest you check out Canonical's careers page where all open positions are listed: https://canonical.com/careers
